[package]
name = "demos"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures =  "0.3.16"
async-std = "1.9.0"
utility = { path = "../utility" }